name: list_selection_widget
description: "List selection widget is a Flutter package that provides a highly customizable dropdown list to select options with ease"
version: 1.0.1
homepage: https://github.com/RichardM20
repository: https://github.com/RichardM20/list_selection_widget_package
 
platforms:
  android:
  ios:
  linux:
  macos:
  web:
  windows:


environment:
  sdk: '>=3.2.3 <4.0.0'
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
 

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
 
 
 
topics:
  - multi-selection
  - list-selection
  - multiple
