import 'package:flutter/material.dart';

import '../model/models.dart';
import 'list_selection_widget_base.dart';

class ListSelectionWidget<T> extends ListSelectionWidgetBase<T> {
  factory ListSelectionWidget.single({
    Key? key,
    required String hintText,
    required List<SelectionItem<T>> listItems,
    required SelectionItem<T>? selectedValue,
    required Function(SelectionItem<T>) onSingleItemSelected,
    bool? hideLines,
    Decoration? decoration,
    IconStyleData? iconStyle,
    TextStyleData? textStyle,
    PaddingData? paddingData,
    double? maxHeight,
    bool autoCollapsed = false,
    Duration animationDuration = const Duration(milliseconds: 200),
    bool initiallyExpanded = false,
    ValueChanged<bool>? onExpansionChanged,
    SelectionTitleBuilder<T>? selectedTitleBuilder,
    SelectionItemBuilder<T>? itemBuilder,
  }) {
    return ListSelectionWidget<T>._(
      key: key,
      hintText: hintText,
      listItems: listItems,
      selectedValue: selectedValue,
      onSingleItemSelected: onSingleItemSelected,
      hideLines: hideLines,
      decoration: decoration,
      iconStyle: iconStyle,
      textStyle: textStyle,
      paddingData: paddingData,
      maxHeight: maxHeight,
      autoCollapsed: autoCollapsed,
      animationDuration: animationDuration,
      initiallyExpanded: initiallyExpanded,
      onExpansionChanged: onExpansionChanged,
      selectedTitleBuilder: selectedTitleBuilder,
      itemBuilder: itemBuilder,
      isMultiSelection: false,
    );
  }

  factory ListSelectionWidget.multi({
    Key? key,
    required String hintText,
    required List<SelectionItem<T>> listItems,
    required List<SelectionItem<T>> multiSelectValues,
    required Function(List<SelectionItem<T>>) onMultiItemsSelected,
    bool? hideLines,
    Decoration? decoration,
    IconStyleData? iconStyle,
    TextStyleData? textStyle,
    PaddingData? paddingData,
    double? maxHeight,
    bool autoCollapsed = false,
    Duration animationDuration = const Duration(milliseconds: 200),
    bool initiallyExpanded = false,
    ValueChanged<bool>? onExpansionChanged,
    SelectionTitleBuilder<T>? selectedTitleBuilder,
    SelectionItemBuilder<T>? itemBuilder,
  }) {
    return ListSelectionWidget<T>._(
      key: key,
      hintText: hintText,
      listItems: listItems,
      multiSelectValues: multiSelectValues,
      onMultiItemsSelected: onMultiItemsSelected,
      hideLines: hideLines,
      decoration: decoration,
      iconStyle: iconStyle,
      textStyle: textStyle,
      paddingData: paddingData,
      maxHeight: maxHeight,
      autoCollapsed: autoCollapsed,
      animationDuration: animationDuration,
      initiallyExpanded: initiallyExpanded,
      onExpansionChanged: onExpansionChanged,
      selectedTitleBuilder: selectedTitleBuilder,
      itemBuilder: itemBuilder,
      isMultiSelection: true,
    );
  }

  @Deprecated(
    'Use ListSelectionWidget.single or ListSelectionWidget.multi instead. '
    'The generic constructor allows invalid selection configurations and will '
    'be removed in a future major version.',
  )
  const ListSelectionWidget({
    Key? key,
    required String hintText,
    required List<SelectionItem<T>> listItems,
    required bool isMultiSelection,
    List<SelectionItem<T>>? multiSelectValues,
    Function(List<SelectionItem<T>>)? onMultiItemsSelected,
    SelectionItem<T>? selectedValue,
    Function(SelectionItem<T>)? onSingleItemSelected,
    bool? hideLines,
    Decoration? decoration,
    IconStyleData? iconStyle,
    TextStyleData? textStyle,
    PaddingData? paddingData,
    double? maxHeight,
    bool autoCollapsed = false,
    Duration animationDuration = const Duration(milliseconds: 200),
    bool initiallyExpanded = false,
    ValueChanged<bool>? onExpansionChanged,
    SelectionTitleBuilder<T>? selectedTitleBuilder,
    SelectionItemBuilder<T>? itemBuilder,
  }) : super(
          key: key,
          hintText: hintText,
          listItems: listItems,
          isMultiSelection: isMultiSelection,
          multiSelectValues: multiSelectValues,
          onMultiItemsSelected: onMultiItemsSelected,
          selectedValue: selectedValue,
          onSingleItemSelected: onSingleItemSelected,
          hideLines: hideLines,
          decoration: decoration,
          iconStyle: iconStyle,
          textStyle: textStyle,
          paddingData: paddingData,
          maxHeight: maxHeight,
          autoCollapsed: autoCollapsed,
          animationDuration: animationDuration,
          initiallyExpanded: initiallyExpanded,
          onExpansionChanged: onExpansionChanged,
          selectedTitleBuilder: selectedTitleBuilder,
          itemBuilder: itemBuilder,
        );

  const ListSelectionWidget._({
    Key? key,
    required String hintText,
    required List<SelectionItem<T>> listItems,
    required bool isMultiSelection,
    List<SelectionItem<T>>? multiSelectValues,
    Function(List<SelectionItem<T>>)? onMultiItemsSelected,
    SelectionItem<T>? selectedValue,
    Function(SelectionItem<T>)? onSingleItemSelected,
    bool? hideLines,
    Decoration? decoration,
    IconStyleData? iconStyle,
    TextStyleData? textStyle,
    PaddingData? paddingData,
    double? maxHeight,
    bool autoCollapsed = false,
    Duration animationDuration = const Duration(milliseconds: 200),
    bool initiallyExpanded = false,
    ValueChanged<bool>? onExpansionChanged,
    SelectionTitleBuilder<T>? selectedTitleBuilder,
    SelectionItemBuilder<T>? itemBuilder,
  }) : super(
          key: key,
          hintText: hintText,
          listItems: listItems,
          isMultiSelection: isMultiSelection,
          multiSelectValues: multiSelectValues,
          onMultiItemsSelected: onMultiItemsSelected,
          selectedValue: selectedValue,
          onSingleItemSelected: onSingleItemSelected,
          hideLines: hideLines,
          decoration: decoration,
          iconStyle: iconStyle,
          textStyle: textStyle,
          paddingData: paddingData,
          maxHeight: maxHeight,
          autoCollapsed: autoCollapsed,
          animationDuration: animationDuration,
          initiallyExpanded: initiallyExpanded,
          onExpansionChanged: onExpansionChanged,
          selectedTitleBuilder: selectedTitleBuilder,
          itemBuilder: itemBuilder,
        );
}
